export class SwiperItem {
  id: number = 0;
  title: string = '';
  coverimage: string = '';
  type: string = '';
  briefcontent: string = '';
  exhibits_id: number = 0;
  status: string = '';
  weigh: number = 0;
  createtime: number = 0;
  updatetime: number = 0;
  status_text: string = '';
}


export class CenterGridItem {
  id: number = 0;
  name: string = '';
  key: string = '';
  status: string = '';
  wigth: number = 0;
  createtime: number = 0;
  updatetime: number = 0;
  status_text: string = '';
}

export class InfoListItem {
  id: number = 0;
  createtime: number = 0;
  updatetime: number = 0;
  title: string = '';
  shortdesc: string = '';
  publishtime: string = '';
  coverimage: string = '';
  audiofile: string = '';
  videofile: string = '';
  briefcontent: string = '';
  price: string = '';
  canpointdata: string = '';
  status: string = '';
  zxviplevel_ids: string = '';
  zxviplevelname: string = '';
  viewcount: number = 0;
  sharecount: number = 0;
  recommend: string = '';
  hot: string = '';
  canpointdata_text: string = '';
  status_text: string = '';
  recommend_text: string = '';
  hot_text: string = '';
}