/**
 * 华为设备有限公司版权所有
 * 根据Apache许可证2.0版(“许可证”)进行许可;
 * 除非遵守许可，否则您不得使用此文件。
 * 您可以在以下网址获得许可证的副本
 * http://www.apache.org/licenses/LICENSE-2.0
 * 除非适用法律要求或书面同意，软件根据许可证分发的*是按“现状”分发的，
 * 不提供任何明示或暗示的保证或条件。
 * 请参阅许可证，了解具体的语言管理权限和许可证下的限制。
 */

/**
 * 所有特性的样式常量.
 */
export default class StyleConstants {
  /**
   *  Login logo component height of the parent 40.
   * 登录标志组件的父组件高度为40
   */
  static readonly LOGIN_LOGO_HEIGHT: string = '40%';

  /**
   *  Login bottom component height of the parent 60.
   * 登录底部组件的父高度60
   */
  static readonly LOGIN_BOTTOM_HEIGHT: string = '60%';

  /**
   * The width or height of the component is spread across the parent component.
   * 组件的宽度或高度分布在父组件上
   */
  static readonly FULL_PARENT: string = '100%';

  /**
   * The width of button.
   * 按钮的宽度
   */
  static readonly BUTTON_WIDTH: string = '90%';

  /**
   * Grid columns of the 4.
   * 网格列的4个
   */
  static readonly GRID_COLUMNS: string = '1fr 1fr 1fr 1fr';

  /**
   * Grid rows of two the 2.
   * 网格的两行2
   */
  static readonly GRID_ROWS: string = '1fr 1fr';

  /**
   * Home grid height of the parent 15.9.
   * 父组件的首页网格高度为15.9%
   */
  static readonly HOME_GRID_HEIGHT: string = '15.9%';

  /**
   * Bar width lg of the parent 7.5.
   * 父组件的条宽度为7.5%
   */
  static readonly BAR_WIDTH_LG: string = '7.5%' ;

  /**
   * Bar default height of the parent 7.2.
   * 父组件的默认条高度为7.2%
   */
  static readonly BAR_DEFAULT_HEIGHT: string = '7.2%';

  /**
   * Bar height lg of the parent 50.
   * 父组件的条高度为50%
   */
  static readonly BAR_HEIGHT_LG: string = '50%';

  /**
   * Component common width of the parent 95.
   * 父组件的组件通用宽度为95%
   */
  static readonly COMMON_WIDTH: string = '95%';

  /**
   * Input length of the account.
   * 输入账号长度
   */
  static readonly INPUT_ACCOUNT_LENGTH: number = 11;

  /**
   * Input length of the password.
   * 输入密码长度
   */
  static readonly INPUT_PASSWORD_LENGTH: number = 8;

  /**
   * Left padding of the input box.
   * 输入框的左内边距
   */
  static readonly INPUT_PADDING_LEFT: number = 12;

  /**
   * Layout weight of number 1.
   * 布局权重数字1
   */
  static readonly WEIGHT_ONE: number = 1;

  /**
   * Common Spacing of Components.
   * 组件的通用间距
   */
  static readonly COMMON_SPACE: number = 12;

  /**
   * Logo margin bottom of the parent 50.
   * 父组件的Logo下外边距为50
   */
  static readonly LOGO_MARGIN_BOTTOM: number = 50;

  /**
   * Item space of the 12.
   * 父组件的间距为12
   */
  static readonly ITEM_SPACE: number = 12;

  /**
   * Grid aspect ratio of the 1.32.
   * 父组件的栅格比为1.32
   */
  static readonly GRID_ASPECT_RATIO: number = 1.32;

  /**
   * Swiper count of the 1.
   * 父组件的轮播图数量为1
   */
  static readonly SWIPER_COUNT_ONE: number = 1;

  /**
   * Swiper count of the 2.
   * 父组件的轮播图数量为2
   */
  static readonly SWIPER_COUNT_TWO: number = 2;

  /**
   * Swiper count of the 3.
   * 父组件的轮播图数量为3
   */
  static readonly SWIPER_COUNT_THREE: number = 3;

  /**
   * List column of the 2.
   * 父组件的列表列数为2
   */
  static readonly LIST_COLUMN_TWO: number = 2;

  /**
   * List column of the 3.
   * 父组件的列表列数为3
   */
  static readonly LIST_COLUMN_THREE: number = 3;

  /**
   * List column of the 4.
   * 父组件的列表列数为4
   */
  static readonly LIST_COLUMN_FOUR: number = 4;

  /**
   * Image list of the 12.
   * 父组件的图片列表列数为12
   */
  static readonly IMAGE_LIST_SPACE: number = 12;
  /**
   * Grid row columns sm of the 4.
   * 父组件的栅格列数为4
   */
  static readonly COLUMNS_SM: number = 4;

  /**
   * Grid row columns md of the 8.
   * 父组件的栅格列数为8
   */
  static readonly COLUMNS_MD: number = 8;

  /**
   * Grid row columns lg of the 12.
   * 父组件的栅格列数为12
   */
  static readonly COLUMNS_LG: number = 12;

  /**
   * Grid gutter of the 12.
   * 父组件的栅格间距为12
   */
  static readonly GRID_GUTTER: number = 12;

  /**
   * Grid col span sm of the 4.
   * 父组件的栅格列数为4
   */
  static readonly SPAN_SM: number = 4;

  /**
   * Grid col span md of the 6.
   * 父组件的栅格列数为6
   */
  static readonly SPAN_MD: number = 6;

  /**
   * Grid col span lg of the 8.
   * 父组件的栅格列数为8
   */
  static readonly SPAN_LG: number = 8;

  /**
   * Grid col offset md of the 1.
   * 父组件的栅格列数为1
   */
  static readonly OFFSET_MD: number = 1;

  /**
   * Grid col offset lg of the 2.
   * 父组件的栅格列数为2
   */
  static readonly OFFSET_LG: number = 2;
}